name: xdman # Using xdman instead of xdm, since 3-letter names aren't allowed for snaps.
base: core20
version: 8.0.29
summary: Powerfull download accelerator and video downloader. 
description: |
  XDM Is a Free and Advanced Download Manger For Linux.
  It is a powerful tool to increase download speeds up to 500%, save videos from popular video streaming websites, resume   
  broken/dead downloads, schedule and convert downloads.
grade: stable
confinement: strict
compression: lzo
license: GPL-2.0+
contact: https://launchpad.net/xdm
issues: https://bugs.launchpad.net/xdm
source-code: https://git.launchpad.net/xdm
architectures:
  - build-on: amd64  

assumes:
  - snapd2.57
   
slots:
  xdman:
    interface: dbus
    bus: session
    name: xdm.app  
    
apps:
  xdman: 
    command: opt/xdman/xdm-app
    desktop: opt/xdman/xdm-app.desktop
    extensions: [gnome-3-38]
    environment:
      PYTHONPATH: ${SNAP}/lib/python3.8/site-packages:${SNAP}/usr/lib/python3/dist-packages
    plugs:
      - home
      - network
      - network-bind
      - network-status
      - browser-support
      - removable-media
      - optical-drive
      - unity7
      - screen-inhibit-control
     
parts:
  ffmpeg:
    plugin: autotools
    source: https://ffmpeg.org/releases/ffmpeg-6.0.tar.xz
    source-checksum: sha256/57be87c22d9b49c112b6d24bc67d42508660e6b718b3db89c44e47e289137082
    autotools-configure-parameters:
      - --prefix=/usr
      - --libdir=/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
      - --disable-debug
      - --disable-doc
      - --disable-static
      - --enable-gpl
      - --enable-shared
      - --disable-ffplay
      - --disable-devices
      - --enable-gnutls
      - --enable-libmp3lame
      - --enable-libvorbis
    build-packages:
      - nasm
      - libmp3lame-dev
      - libvorbis-dev
    stage-packages:
      - libmp3lame0
    prime:
      - -usr/include
      - -usr/lib/*/pkgconfig
      - -usr/share/ffmpeg/examples
      - -usr/share/doc

  yt-dlp:
    after: [ffmpeg]
    plugin: python
    source: https://github.com/yt-dlp/yt-dlp/releases/download/2023.07.06/yt-dlp.tar.gz
    source-checksum: sha256/6d2115b84b6c11867f92cf4c23705b536bfa0ba9d538b1885f52da6756f8c980
    python-packages:
      - pyxattr==0.8.1
    build-environment:
      - PATH: ${SNAPCRAFT_PART_INSTALL}/bin:${PATH}
      - PYTHONPATH: ""
    override-pull: |
      snapcraftctl pull
      sed -i 's/^certifi\b/#\0/' requirements.txt
    stage:
      - -bin/activate*
      - -bin/Activate*
      - -bin/python*
      - -bin/pip*
      - -pyvenv.cfg
      - -share/python-wheels
      - -share/doc
      - -share/man
      - -lib/**/setuptools*
      - -lib/**/pip*
      - -lib/**/wheel*
      - -include
      
  xdm:
    source: https://github.com/subhra74/xdm/releases/download/$SNAPCRAFT_PROJECT_VERSION/xdman_gtk_$SNAPCRAFT_PROJECT_VERSION_$SNAPCRAFT_TARGET_ARCH.deb
    after: [yt-dlp]
    plugin: dump
    override-prime: |
      snapcraftctl prime
      sed -e 's|Icon=/opt/xdman/xdm-logo.svg|Icon=${SNAP}/opt/xdman/xdm-logo.svg|' -i opt/xdman/xdm-app.desktop
      sed -e 's|Exec=env GTK_USE_PORTAL=1 /opt/xdman/xdm-app %U|Exec=opt/xdman/xdm-app %U|' -i opt/xdman/xdm-app.desktop    
    stage-packages:
      - curl 
      - liblttng-ust0
    prime:
      - opt
      - usr/bin
      - usr/lib
      - -usr/bin/xdman
      - -usr/lib/sasl2
      - -usr/lib/*/gdk-pixbuf*

  cleanup:
    after:  
      - xdm
    plugin: nil
    build-snaps: 
      - gnome-3-38-2004
      - core20
      - gtk-common-themes
    override-prime: |
      set -eux
      for snap in "gnome-3-38-2004" "core20" "gtk-common-themes"; do
          cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done  
