name: xdman # Using xdman instead of xdm, since 3-letter names aren't allowed for snaps.
base: core22
version: 8.0.29
summary: Powerfull download accelerator and video downloader.
description: |
  XDM Is a Free and Advanced Download Manger For Linux.
  It is a powerful tool to increase download speeds up to 500%, save videos from popular video streaming websites, resume
  broken/dead downloads, schedule and convert downloads.
grade: stable
confinement: strict
compression: lzo
license: GPL-2.0+
contact:
  - https://launchpad.net/xdm
  - https://github.com/sameersharma2006/xdman-snap
issues:
  - https://bugs.launchpad.net/xdm
  - https://github.com/sameersharma2006/xdman-snap/issues
source-code: https://git.launchpad.net/xdm/tree/snapcraft.yaml
architectures:
  - build-on: amd64

lint:
  ignore:
    - classic
    - library:
      - opt/xdman/libcoreclrtraceptprovider.so

slots:
  xdman:
    interface: dbus
    bus: session
    name: xdm.app # Invalid DBUS Naming Convention Used By Upstream.

apps:
  xdman:
    command: opt/xdman/xdm-app
    desktop: opt/xdman/xdm-app.desktop
    extensions: [gnome]
    environment:
      DISABLE_WAYLAND: 1
      PYTHONPATH: ${SNAP}/lib/python3.10/site-packages:${SNAP}/usr/lib/python3/dist-packages
    plugs:
      - home
      - network
      - network-bind
      - network-status
      - removable-media
      - unity7
      - screen-inhibit-control

parts:
  ffmpeg:
    plugin: autotools
    source: https://ffmpeg.org/releases/ffmpeg-4.4.4.tar.gz
    autotools-configure-parameters:
      - --prefix=/usr
      - --libdir=/usr/lib/$CRAFT_ARCH_TRIPLET
      - --disable-debug
      - --disable-doc
      - --disable-static
      - --enable-gpl
      - --enable-shared
      - --disable-ffplay
      - --disable-devices
      - --enable-gnutls
      - --enable-libmp3lame
      - --enable-libvorbis
    build-packages:
      - nasm
      - libmp3lame-dev
      - libvorbis-dev
    stage-packages:
      - libmp3lame0
    prime:
      - -usr/include
      - -usr/lib/*/pkgconfig
      - -usr/share/ffmpeg/examples
      - -usr/share/doc

  yt-dlp:
    after: [ffmpeg]
    plugin: python
    source: https://github.com/yt-dlp/yt-dlp/releases/download/2024.05.27/yt-dlp.tar.gz
    build-environment:
      - PATH: ${CRAFT_PART_INSTALL}/bin:${PATH}
      - PYTHONPATH: ""
    prime:
      - -bin/activate*
      - -bin/Activate*
      - -bin/python*
      - -bin/pip*
      - -pyvenv.cfg
      - -share/python-wheels
      - -share/doc
      - -share/man
      - -lib/**/setuptools*
      - -lib/**/pip*
      - -lib/**/wheel*
      - -include

  xdm:
    source: https://github.com/subhra74/xdm/releases/download/$SNAPCRAFT_PROJECT_VERSION/xdman_gtk_$SNAPCRAFT_PROJECT_VERSION_$CRAFT_TARGET_ARCH.deb
    after: [yt-dlp]
    plugin: dump
    override-prime: |
      craftctl default
      sed -e 's|Icon=/opt/xdman/xdm-logo.svg|Icon=${SNAP}/opt/xdman/xdm-logo.svg|' -i opt/xdman/xdm-app.desktop
      sed -e 's|Exec=env GTK_USE_PORTAL=1 /opt/xdman/xdm-app %U|Exec=opt/xdman/xdm-app %U|' -i opt/xdman/xdm-app.desktop
    prime:
      - opt
