name: build-test
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  snap:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: snapcore/action-build@v1
      id: snapcraft
    - uses: actions/upload-artifact@v4
      with:
        name: 'snap'
        path: ${{ steps.snapcraft.outputs.snap}}
